version: '3.8'  # Ensure you use a supported version
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure the name matches your Dockerfile
    ports:
      - "8000:8000"  # Properly formatted port mapping
    volumes:
      - .:/app  # Ensure the correct volume path
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5433:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
   
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: